---
- name: 3.1.1 | Ensure IPv6 status is identified
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6    
  when:
    - rhel8cis_rule_3_1_1_enabled
    - not rhel8cis_ipv6_needed
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true

- name: 3.1.2 | Ensure wireless interfaces are disabled
  when:
    - rhel8cis_rule_3_1_2_enabled
    - _rhel8cis_server
  become: true
  block:
    - name: 3.1.2 | Ensure wireless interfaces are disabled | Check if wifi is enabled
      ansible.builtin.command: nmcli radio wifi
      changed_when: false
      failed_when: false
      register: _rhel8cis_wifi_status

    - name: 3.1.2 | Ensure wireless interfaces are disabled | Disable wifi
      when:
        - _rhel8cis_wifi_status.stdout.find('enabled') != -1
      ansible.builtin.command: nmcli radio all off
      changed_when: true
      failed_when: false

- name: 3.1.3 | Ensure bluetooth services are not in use
  when:
    - rhel8cis_rule_3_1_3_enabled
    - _rhel8cis_server or
      _rhel8cis_workstation_level2 or
      rhel8cis_rule_3_1_3_force
  become: true
  block:
    - name: 3.1.3 | Ensure bluetooth services are not in use | bluez package
      ansible.builtin.dnf:
        name:
          - bluez
        state: "{{ _rhel8cis_bluez_state }}"

    - name: 3.1.3 | Ensure bluetooth services are not in use | bluetooth.service
      when:
        - rhel8cis_bluez_needed
      ansible.builtin.systemd_service:
        name: bluetooth.service
        state: stopped
        enabled: false
        masked: true
