---
- name: 6.2.11 | Ensure local interactive user dot files access is configured | Remove senstive files
  loop:
    - "{{ user.dir }}/.forward"
    - "{{ user.dir }}/.rhosts"
    - "{{ user.dir }}/.netrc"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent

- name: 6.2.11 | Ensure local interactive user dot files access is configured | Get list of dot files
  become: true
  ansible.builtin.find:
    paths: "{{ user.dir }}"
    patterns:
      - '.*'
    excludes:
      - .bash_history
    file_type: file
    recurse: true
  register: _rhel8cis_user_dot_files

- name: 6.2.11 | Ensure local interactive user dot files access is configured | Set permissions on dot files
  loop: "{{ _rhel8cis_user_dot_files.files }}"
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ user.id }}"
    group: "{{ user.id }}"
    mode: '0640'
  loop_control:
    label: "{{ item.path }}"

- name: 6.2.11 | Ensure local interactive user dot files access is configured | Check .bash_history
  become: true
  ansible.builtin.stat:
    path: "{{ user.dir }}/.bash_history"
  register: _rhel8cis_bash_history

- name: 6.2.11 | Ensure local interactive user dot files access is configured | Set permissions on .bash_history
  when:
    - _rhel8cis_bash_history.stat.exists
  become: true
  ansible.builtin.file:
    path: "{{ user.dir }}/.bash_history"
    owner: "{{ user.id }}"
    group: "{{ user.id }}"
    mode: '0600'
    state: file
  
- name: 6.2.11 | Ensure local interactive user dot files access is configured | Create .bash_history
  when:
    - not _rhel8cis_bash_history.stat.exists
  become: true
  ansible.builtin.file:
    path: "{{ user.dir }}/.bash_history"
    owner: "{{ user.id }}"
    group: "{{ user.id }}"
    mode: '0600'
    state: touch
