---
- name: |
    1.7.1 | Ensure message of the day is configured properly
    1.7.4 | Ensure access to /etc/motd is configured
  when:
    - rhel8cis_rule_1_7_1_enabled or
      rhel8cis_rule_1_7_4_enabled
  become: true
  block:
    - name: |
        1.7.1 | Ensure message of the day is configured properly
        1.7.4 | Ensure access to /etc/motd is configured
      when:
        - rhel8cis_use_motd
      ansible.builtin.copy:
        content: "{{ rhel8cis_motd_banner }}"
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

    - name: |
        1.7.1 | Ensure message of the day is configured properly
        1.7.4 | Ensure access to /etc/motd is configured
      when:
        - not rhel8cis_use_motd
      ansible.builtin.file:
        path: /etc/motd
        state: absent

- name: |
    1.7.2 | Ensure local login warning banner is configured properly
    1.7.5 | Ensure access to /etc/issue is configured
  when:
    - rhel8cis_rule_1_7_2_enabled or
      rhel8cis_rule_1_7_5_enabled
  become: true
  block:
    - name: |
        1.7.2 | Ensure local login warning banner is configured properly
        1.7.5 | Ensure access to /etc/issue is configured
      when:
        - rhel8cis_use_issue
      ansible.builtin.copy:
        content: "{{ rhel8cis_issue_banner }}"
        dest: /etc/issue
        owner: root
        group: root
        mode: '0644'

    - name: |
        1.7.2 | Ensure local login warning banner is configured properly
        1.7.5 | Ensure access to /etc/issue is configured
      when:
        - not rhel8cis_use_issue
      ansible.builtin.file:
        path: /etc/issue
        state: absent

- name: |
    1.7.3 | Ensure remote login warning banner is configured properly
    1.7.6 | Ensure access to /etc/issue.net is configured
  when:
    - rhel8cis_rule_1_7_3_enabled or
      rhel8cis_rule_1_7_6_enabled
  become: true
  block:
    - name: |
        1.7.3 | Ensure remote login warning banner is configured properly
        1.7.6 | Ensure access to /etc/issue.net is configured
      when:
        - rhel8cis_use_issue_net
      ansible.builtin.copy:
        content: "{{ rhel8cis_issue_net_banner }}"
        dest: /etc/issue.net
        owner: root
        group: root
        mode: '0644'

    - name: |
        1.7.3 | Ensure remote login warning banner is configured properly
        1.7.6 | Ensure access to /etc/issue.net is configured
      when:
        - not rhel8cis_use_issue_net
      ansible.builtin.file:
        path: /etc/issue.net
        state: absent
