---
- name: Execute the 1.1.1.x tasks
  ansible.builtin.import_tasks: 1.1.1.x.yml

- name: Execute the 1.1.2.x tasks
  ansible.builtin.import_tasks: 1.1.2/main.yml

- name: Execute the 1.2.x tasks
  ansible.builtin.import_tasks: 1.2/main.yml

- name: Execute the 1.3.x tasks
  ansible.builtin.import_tasks: 1.3.x.yml

- name: Execute the 1.4.x tasks
  ansible.builtin.import_tasks: 1.4.x.yml

- name: Execute the 1.5.x tasks
  ansible.builtin.import_tasks: 1.5.x.yml

- name: Execute the 1.6.x tasks
  ansible.builtin.import_tasks: 1.6.x.yml

- name: Execute the 1.7.x tasks
  ansible.builtin.import_tasks: 1.7.x.yml

- name: Execute the 1.8.x tasks
  ansible.builtin.import_tasks: 1.8.x.yml
