---
- name: 2.1.1 | Ensure time synchronization is in use
  when:
    - rhel8cis_rule_2_1_1_enabled
  become: true
  ansible.builtin.package:
    name: chrony
    state: present

- name: 2.1.2 | Ensure chrony is configured
  when:
    - rhel8cis_rule_2_1_2_enabled
  become: true
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - _rhel8cis_restart_chronyd

- name: 2.1.3 | Ensure chrony is not run as the root user
  when:
    - rhel8cis_rule_2_1_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/chronyd
    regexp: '^OPTIONS='
    line: 'OPTIONS="-u chrony"'
  notify:
    - _rhel8cis_restart_chronyd
