---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: server
    box: jtarpley/rocky8_base
    memory: 2048
    cpus: 2
  - name: workstation
    box: jtarpley/rocky8_ws_base
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ./hosts
      host_vars: ./host_vars/
      group_vars: ./group_vars/
verifier:
  name: ansible
