---
- name: |
    1.1.2.2.1 | Ensure /dev/shm is a separate partition
    1.1.2.2.2 | Ensure nodev option set on /dev/shm partition
    1.1.2.2.3 | Ensure nosuid option set on /dev/shm partition
    1.1.2.2.4 | Ensure noexec option set on /dev/shm partition
  when:
    - rhel8cis_rule_1_1_2_2_1_enabled or
      rhel8cis_rule_1_1_2_2_2_enabled or
      rhel8cis_rule_1_1_2_2_3_enabled or
      rhel8cis_rule_1_1_2_2_4_enabled
  become: true
  ansible.posix.mount:
    src: tmpfs
    name: /dev/shm
    fstype: tmpfs
    opts: "{{ rhel8cis_dev_shm_mount_opts | join(',') }}"
    state: present
  notify:
    - _rhel8cis_reboot
