---
- name: |
    1.1.2.1.1 | Ensure /tmp is a separate partition
    1.1.2.1.2 | Ensure nodev option set on /tmp partition
    1.1.2.1.3 | Ensure nosuid option set on /tmp partition
    1.1.2.1.4 | Ensure noexec option set on /tmp partition
  when:
    - rhel8cis_rule_1_1_2_1_1_enabled or
      rhel8cis_rule_1_1_2_1_2_enabled or
      rhel8cis_rule_1_1_2_1_3_enabled or
      rhel8cis_rule_1_1_2_1_4_enabled
  become: true
  ansible.posix.mount:
    src: tmpfs
    name: /tmp
    fstype: tmpfs
    opts: "{{ rhel8cis_tmp_mount_opts | join(',') }}"
    state: present
  notify:
    - _rhel8cis_reboot
