---
- name: 4.5.1.1 | Ensure strong password hashing algorithm is configured
  loop:
    - path: /etc/libuser.conf
      regexp: '^#?\s?crypt_style ='
      line: 'crypt_style = sha512'
    - path: /etc/login.defs
      regexp: '^#?\s?ENCRYPT_METHOD'
      line: 'ENCRYPT_METHOD SHA512'
  when:
    - rhel8cis_rule_4_5_1_1_enabled
  become: true
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"

- name: 4.5.1.2 | Ensure password expiration is 365 days or less
  when:
    - rhel8cis_rule_4_5_1_2_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^#?\s?PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS 365'

- name: 4.5.1.3 | Ensure password expiration warning days is 7 or more
  when:
    - rhel8cis_rule_4_5_1_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^#?\s?PASS_WARN_AGE'
    line: 'PASS_WARN_AGE 7'

- name: 4.5.1.4 | Ensure inactive password lock is 30 days or less
  when:
    - rhel8cis_rule_4_5_1_4_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/useradd
    regexp: '^INACTIVE'
    line: 'INACTIVE={{ rhel8cis_inactive_password_lock_days }}'

- name: 4.5.1.5 | Ensure all users last password change date is in the past
  when:
    - rhel8cis_rule_4_5_1_5_enabled
  become: true
  block:
    - name: 4.5.1.5 | Ensure all users last password change date is in the past | Get current date/time
      ansible.builtin.shell: echo $(($(date --utc --date "$1" +%s)/86400))
      changed_when: false
      failed_when: false
      register: _rhel8cis_current_date_time

    - name: 4.5.1.5 | Ensure all users last password change date is in the past | Get users with future password date
      ansible.builtin.shell: |
        cat /etc/shadow | awk -F: '{if($3>{{ _rhel8cis_current_date_time.stdout }})print$1}'
      changed_when: false
      failed_when: false
      register: _rhel8cis_future_password_users
      tags:
        - always
        - skip_ansible_lint
      
    - name: 4.5.1.5 | Ensure all users last password change date is in the past | Warn
      when:
        - _rhel8cis_future_password_users.stdout_lines | length > 0
      ansible.builtin.include_tasks: ../add-warning.yml
      vars:
        _rhel8cis_warning_rule: '4.5.1.5'
        _rhel8cis_warning_description: >-
          '{{ _rhel8cis_future_password_users.stdout_lines | join(",") }} have invalid password dates.'

- name: 4.5.2.1 | Ensure default group for the root account is GID 0
  when:
    - rhel8cis_rule_4_5_2_1_enabled
  become: true
  block:
    - name: 4.5.2.1 | Ensure default group for the root account is GID 0 | Check GID
      ansible.builtin.shell: "awk -F: '$1==\"root\"{print $1\":\"$4}' /etc/passwd"
      changed_when: false
      register: _rhel8cis_root_group

    - name: 4.5.2.1 | Ensure default group for the root account is GID 0 | Change
      when:
        - _rhel8cis_root_group.stdout != 'root:0'
      ansible.builtin.command: usermod -g 0 root
      changed_when: true

- name: 4.5.2.2 | Ensure root user umask is configured
  when:
    - rhel8cis_rule_4_5_2_2_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /root/.bash_profile
    regexp: '^#?\s?umask'
    line: 'umask 0027'

- name: "Parse /etc/passwd to variable"
  block:
    - name: Get /etc/passwd contents
      check_mode: false
      ansible.builtin.command: cat /etc/passwd
      changed_when: false
      register: _rhel8cis_passwd_file_audit

    - name: "Parse contents to variable"
      ansible.builtin.set_fact:
        _rhel8cis_passwd: "{{ _rhel8cis_passwd_file_audit.stdout_lines | map('regex_replace', ld_passwd_regex, ld_passwd_yaml) | map('from_yaml') | list }}"
      vars:
        ld_passwd_regex: >-
          ^(?P<id>[^:]*):(?P<password>[^:]*):(?P<uid>[^:]*):(?P<gid>[^:]*):(?P<gecos>[^:]*):(?P<dir>[^:]*):(?P<shell>[^:]*)
        ld_passwd_yaml: |
          id: >-4
              \g<id>
          password: >-4
              \g<password>
          uid: \g<uid>
          gid: \g<gid>
          gecos: >-4
              \g<gecos>
          dir: >-4
              \g<dir>
          shell: >-4
              \g<shell>

- name: 4.5.2.3 | Ensure system accounts are secured
  when:
    - rhel8cis_rule_4_5_2_3_enabled
  become: true
  block:
    - name: 4.5.2.3 | Ensure system accounts are secured | Set nologin shell
      loop: "{{ _rhel8cis_passwd }}"
      when:
        - item.id != "halt"
        - item.id != "shutdown"
        - item.id != "sync"
        - item.id != "root"
        - item.id != "nfsnobody"
        - item.uid < 1000
        - item.shell != "/bin/false"
        - item.shell != "/usr/sbin/nologin"
        - item.shell != "/sbin/nologin"
      ansible.builtin.user:
        name: "{{ item.id }}"
        shell: /usr/sbin/nologin
      loop_control:
        label: "{{ item.id }}"

    - name: 4.5.2.3 | Ensure system accounts are secured | Lock password
      loop: "{{ _rhel8cis_passwd }}"
      when:
        - item.id != "halt"
        - item.id != "shutdown"
        - item.id != "sync"
        - item.id != "root"
        - item.id != "nfsnobody"
        - item.uid < 1000
      ansible.builtin.user:
        name: "{{ item.id }}"
        password: "*"
        password_lock: true
      loop_control:
        label: "{{ item.id }}"

- name: 4.5.2.4 | Ensure root password is set
  when:
    - rhel8cis_rule_4_5_2_4_enabled
  ansible.builtin.include_tasks: ../add-warning.yml
  vars:
    _rhel8cis_warning_rule: '4.5.2.4'
    _rhel8cis_warning_description: "The root password will not be set by this role. Please set it manually."

- name: 4.5.3.1 | Ensure nologin is not listed in /etc/shells
  when:
    - rhel8cis_rule_4_5_3_1_enabled
    - _rhel8cis_level2 or rhel8cis_rule_4_5_3_1_force
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    regexp: '/nologin\b'
    state: absent

- name: 4.5.3.2 | Ensure default user shell timeout is configured
  when:
    - rhel8cis_rule_4_5_3_2_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/profile.d/timeout.sh
    create: true
    line: 'TMOUT=600'
    owner: root
    group: root
    mode: '0755'

- name: 4.5.3.3 | Ensure default user umask is configured
  when:
    - rhel8cis_rule_4_5_3_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/profile.d/umask.sh
    create: true
    line: 'umask 0027'
    owner: root
    group: root
    mode: '0755'
